#!/usr/bin/env bash

function _etcd_profile {
  local shome="${_etcd_home:-"$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  PATH="$shome/bin:$PATH"

  ETCD_VERSION="${ETCD_VERSION:-3.1.2}"
}

_etcd_profile
