#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_etcd="$(etcd --version 2>/dev/null | grep 'etcd Version' | awk '{print $3}' || true)"
  jq -n --arg etcd "$ver_etcd" '{etcd: $etcd}'
}

version "$@"
